export default defineEventHandler((event) => {
  return [{
    id: 1,
    brand: "Koenigsegg",
    model: "GT-R",
    typeCar: "Sport",
    capacity: 2,
    steering: "Manual",
    gasoline: 90,
    pricePerDay: 99,
    oldPricePerDay: 0,
    description: "",
    image: "car-1",
    isAvailable: true,
    review: 4.2,
    liked: false
  },
  {
    id: 2,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "SUV",
    capacity: 4,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 96.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-2",
    isAvailable: false,
    review: 3.7,
    liked: true
  },
  {
    id: 3,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "MPV",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80,
    oldPricePerDay: 100,
    description: "",
    image: "car-3",
    isAvailable: true,
    review: 4.7,
    liked: false
  },
  {
    id: 4,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Sedan",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 72.00,
    oldPricePerDay: 90,
    description: "",
    image: "car-4",
    isAvailable: false,
    review: 3.1,
    liked: true
  },
  {
    id: 5,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Coupe",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-1",
    isAvailable: true,
    review: 4.9,
    liked: false
  },
  {
    id: 6,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Hatchback",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-2",
    isAvailable: false,
    review: 3.5,
    liked: true
  },
  {
    id: 7,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Sport",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-3",
    isAvailable: true,
    review: 4.0,
    liked: false
  },
  {
    id: 8,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Sport",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-4",
    isAvailable: false,
    review: 3.7,
    liked: true
  },
  {
    id: 9,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Sport",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-1",
    isAvailable: true,
    review: 4.1,
    liked: false
  },
  {
    id: 10,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Sport",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-2",
    isAvailable: false,
    review: 3.3,
    liked: true
  },
  {
    id: 11,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Sport",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-3",
    isAvailable: true,
    review: 4.2,
    liked: false
  },
  {
    id: 12,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Sport",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-4",
    isAvailable: false,
    review: 3.2,
    liked: true
  },
  {
    id: 13,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Sport",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-1",
    isAvailable: true,
    review: 4.9,
    liked: false
  },
  {
    id: 14,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Sport",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-2",
    isAvailable: false,
    review: 3.1,
    liked: true
  },
  {
    id: 15,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Sport",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-3",
    isAvailable: true,
    review: 4.7,
    liked: false
  },
  {
    id: 16,
    brand: "Nissan",
    model: "GT-R",
    typeCar: "Sport",
    capacity: 2,
    steering: "Manual",
    gasoline: 70,
    pricePerDay: 80.00,
    oldPricePerDay: 0,
    description: "",
    image: "car-4",
    isAvailable: false,
    review: 3.6,
    liked: true
  }]
})
